### ISSUE TITLE
QUESTION: Adding functionality to BTraceUtils

### ISSUE THREAD

**Issue by gm281** [jbachorik/btrace#117]
Hello,

I'd like to extend BTraceUtils, to let probe code log messages to log4j (as set up and used by the application I'm injecting).

I thought I'd work in the following way:
* I add extra code to BTraceUtils to perform the actual logging, see [1]
* I call BTraceUtils.logMessage("some message") from the probe code
* in order to compile BTraceUtils I added log4j jar next to btrace-asm-5.0.2.jar, and updated bulid.xml to treat log4j exactly the same as btrace-asm.

This worked relatively well. Everything compiled etc. However, the problem is that in the injected application, I'm getting another version of log4j Logger class loaded. This means none of the existing configuration for log4j is inherited, and consequently nothing gets logged (I only get a complaint from log4j that it's not initialised, printed to stdout).

Then I thought that maybe if I removed log4j classes from btrace-boot.jar, the JVM would have to fallback onto the versions of the classes already loaded. But that didn't work. Instead, I'm getting NoClassDefFoundError[2].

I don't understand the class loading semantics well enough to know why the new version of the class is required. Could someone help.

Also, if there is a better approach to all of this, I'd love to hear.

It'd be really powerful to allow certain operations, which are deemed to be safe, such as logging. That way not only I can debug my application in production without having to suspend it, but I can add extra functionality dynamically too.

Thanks!
Gregor

[1]
```
+ public static void logMessage(String message) {
+ Logging.logMessage(message);
+ }
+
+ public static class Logging {
+ public static void logMessage(String message) {
+ Logger.getLogger(Logging.class).info(message);
+ }
+ }
```

[2]
```
java.lang.NoClassDefFoundError: org/apache/log4j/LogManager
at com.sun.btrace.BTraceUtils$Logging.logMessage(BTraceUtils.java:3244)
at com.sun.btrace.BTraceUtils.logMessage(BTraceUtils.java:3237)
at SleepyLoop.$btrace$BTraceLogger$callMade(SleepyLoop.java:18)
at SleepyLoop.testMethod(SleepyLoop.java)
at SleepyLoop.main(SleepyLoop.java:37)
```

**Comment by jbachorik** [comment]
This is all caused by the classloader mismatch.

By adding the logging classes to **btrace-boot.jar** you are effectively loading the logging classes by the bootstrap class loader. This is so because **BTraceUtils** is loaded by the bootstrap classloader in order  to be accessible from eg. the core java classes.

Your application, on the other hand, loads its own copies of the logging classes using (most probably) the application class loader (or a dedicated class loader - in case of eg. a web/enterprise app). Thanks to this you will end up with two copies - the bootstrap copy (most probably not configured, using just defaults)  used from the instrumented code, and the application level (properly configured) copy used throughout your application (non-instrumented code).

The only remedy I can think of is to use an accessor class which would, by the means of core reflection, check for the accessibility of the logging classes and in case they are accessible it would forward the logging calls to the logging framework. This would still require putting the logging classes on bootclasspath via **-Xbootclasspath/a** so the logging classes are defined by the bootstrap classloader and properly shared.

Any other solution would require a big portion of class loading magic. But you are welcome to experiment :wink: 

-JB-

**Comment by gm281** [comment]
Thanks for the answer Jaroslav,

Just to clarify, you propose to implement the reflection based logging 'proxy' in the *app*. Similarly, it is the app that needs to be launched with `-Xbootclasspath/a`. Assuming I understood that correctly I'll give that a go in my proof of concept.

Thanks
Gregor

**Comment by jbachorik** [comment]
Hi Gregor,

yes, you understand it correctly.

Cheers,

-JB-
